// <auto-generated />
using System;
using BateauEcole.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BateauEcole.Api.src.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902174542_AddPermitPurchases")]
    partial class AddPermitPurchases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BateauEcole.Api.Models.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_availability_slots");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_availability_slots_instructor_id");

                    b.ToTable("availability_slots", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_bookings_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_contact_messages");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.ExamDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permit_type");

                    b.HasKey("Id")
                        .HasName("pk_exam_dates");

                    b.ToTable("exam_dates", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.PrimitiveCollection<string[]>("Specialties")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("specialties");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_instructors");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_instructors_user_id");

                    b.ToTable("instructors", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IncludesPractical")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_practical");

                    b.Property<bool>("IncludesTheory")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_theory");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bundle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_permits");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_permits_slug");

                    b.ToTable("permits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82275f75-b258-4ba6-a7e2-9d28dfb01a63"),
                            Description = "Dès 16 ans. Navigation de jour comme de nuit, dans la limite de 6 milles d'un abri (11 km), sans limite de puissance ni de taille de bateau. Valable à vie, en France et à l'international. 5h de code en salle + 3h30 de pratique (dont 2h à la barre). Inclus : inscription (numéro OEDIPP), livre de code, livret du candidat, tests en ligne illimités, convocation à l'examen. Tarif : 250 € + 30 € d'examen + 78 € de droits fiscaux.",
                            IncludesPractical = true,
                            IncludesTheory = true,
                            IsBundle = false,
                            Name = "Permis Mer Côtier",
                            Price = 358m,
                            Slug = "permis-mer-cotier-complet"
                        },
                        new
                        {
                            Id = new Guid("3e1d77c2-305f-42d6-b58b-a48a8898bc6f"),
                            Description = "Extension réservée aux titulaires du permis Mer option côtière. Navigation de jour comme de nuit, sans limite de distance, de puissance ni de taille de bateau. Valable à vie, en France et à l'international. Inclus : livre de code, cahier d'exercice, cours en vidéo, matériel de navigation (carte, rapporteur, compas). Tarif : 235 € + 38 € de droits fiscaux.",
                            IncludesPractical = false,
                            IncludesTheory = true,
                            IsBundle = false,
                            Name = "Permis Mer Hauturier",
                            Price = 273m,
                            Slug = "permis-mer-hauturier"
                        },
                        new
                        {
                            Id = new Guid("14d33286-b681-457d-b198-75141ded90cc"),
                            Description = "Réservé aux titulaires d'un permis Mer. Permet de naviguer sur rivières, canaux et lacs avec un bateau de moins de 20 m, sans limite de puissance. Valable à vie, en France et à l'international. Inclus : livre de code, tests en ligne illimités. Tarif : 70 € + 30 € de droits fiscaux.",
                            IncludesPractical = false,
                            IncludesTheory = true,
                            IsBundle = false,
                            Name = "Permis Eaux Intérieures (Fluvial) — code seul",
                            Price = 100m,
                            Slug = "permis-eaux-interieures-code-seul"
                        },
                        new
                        {
                            Id = new Guid("b134c5b1-15c3-4243-820a-7eea7e851ad0"),
                            Description = "Réservé aux titulaires du permis Eaux Intérieures (fluvial). Le code peut se préparer en autonomie ou avec les cours en salle. Inclus : livre de code, tests en ligne illimités. Tarif : à partir de 70 € en autonomie (100 € tout compris) ou 120 € avec cours en salle (150 € tout compris).",
                            IncludesPractical = false,
                            IncludesTheory = true,
                            IsBundle = false,
                            Name = "Permis Mer Côtier — code seul",
                            Price = 150m,
                            Slug = "permis-mer-cotier-code-seul"
                        },
                        new
                        {
                            Id = new Guid("8fca7261-0221-4437-99b0-314bcb87ab4b"),
                            Description = "Permis Mer côtier (code + pratique) + code Eaux Intérieures (fluvial) en autonomie. Tarif : 305 € + 30 € d'examen + 78 € de droits fiscaux.",
                            IncludesPractical = true,
                            IncludesTheory = true,
                            IsBundle = true,
                            Name = "Permis Côtier complet + Eaux Intérieures",
                            Price = 443m,
                            Slug = "permis-cotier-complet-eaux-interieures"
                        },
                        new
                        {
                            Id = new Guid("995b4fbf-8702-4e33-8f72-383e3bc634a6"),
                            Description = "Permis Mer côtier complet (code + pratique) + extension Hauturier en autonomie. Tarif : 455 € + 30 € d'examen + 78 € + 38 € de droits fiscaux.",
                            IncludesPractical = true,
                            IncludesTheory = true,
                            IsBundle = true,
                            Name = "Permis Côtier complet + Hauturier",
                            Price = 601m,
                            Slug = "permis-cotier-complet-hauturier"
                        },
                        new
                        {
                            Id = new Guid("463ae33b-1607-4bad-a539-0d4e872b8fbc"),
                            Description = "Réservé aux titulaires du permis Mer côtier. Les deux codes en autonomie. Tarif : 285 € + 30 € d'examen + 38 € de droits fiscaux.",
                            IncludesPractical = false,
                            IncludesTheory = true,
                            IsBundle = true,
                            Name = "Permis Hauturier + Eaux Intérieures (code seul)",
                            Price = 333m,
                            Slug = "permis-hauturier-eaux-interieures-code"
                        },
                        new
                        {
                            Id = new Guid("6d792daa-b670-44a8-abec-ed45bd20bfdf"),
                            Description = "Permis Côtier complet (code + pratique) + code Eaux Intérieures + code Hauturier, en autonomie pour les deux extensions. Tarif : 495 € + 30 € d'examen + 78 € + 38 € de droits fiscaux.",
                            IncludesPractical = true,
                            IncludesTheory = true,
                            IsBundle = true,
                            Name = "Les 3 permis bateau",
                            Price = 671m,
                            Slug = "les-3-permis-bateau"
                        });
                });

            modelBuilder.Entity("BateauEcole.Api.Models.PermitPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid")
                        .HasColumnName("permit_id");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_permit_purchases");

                    b.HasIndex("PermitId")
                        .HasDatabaseName("ix_permit_purchases_permit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_permit_purchases_user_id");

                    b.ToTable("permit_purchases", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid")
                        .HasColumnName("permit_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_sessions_instructor_id");

                    b.HasIndex("PermitId")
                        .HasDatabaseName("ix_sessions_permit_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("BateauEcole.Api.Models.AvailabilitySlot", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_slots_instructors_instructor_id");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Booking", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_sessions_session_id");

                    b.HasOne("BateauEcole.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Instructor", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BateauEcole.Api.Models.PermitPurchase", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.Permit", "Permit")
                        .WithMany()
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permit_purchases_permits_permit_id");

                    b.HasOne("BateauEcole.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permit_purchases_users_user_id");

                    b.Navigation("Permit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BateauEcole.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BateauEcole.Api.Models.Session", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_instructors_instructor_id");

                    b.HasOne("BateauEcole.Api.Models.Permit", "Permit")
                        .WithMany()
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_permits_permit_id");

                    b.Navigation("Instructor");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BateauEcole.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
